version: '3'

services:
    app:
        build: "."
        container_name: "fiszki"
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www

    database:
        image: mysql/mysql-server:latest
        container_name: "fiszki_mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "fiszki"
